OnlineWebShop/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using webshop.Models;
using webshop.Logic;

namespace webshop.Controllers
{
    public class CustomersController : Controller
    {
        private OnlineStoreEntities db = new OnlineStoreEntities();

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Kunder.ToList());
        }
        public ActionResult SignIn()
        {
          return View();
        }
    // GET: Customers/Details/5
    public ActionResult Details(int? id = 0)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kunde kunde = db.Kunder.Find(id);
            if (kunde == null)
            {
                return HttpNotFound();
            }
            return View(kunde);
        }

        // GET: Customers/Create
    //    public ActionResult Create(Kunde best)
    //{
    //    var db = new DB();
    //  if (ModelState.IsValid)
    //  {
    //    if (db.SettInnNyKunde(best))
    //    {
    //      return RedirectToAction("Index");
    //    }
    //    return View();
    //  }
    //}

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "KId,Navn,Adresse,Epost,Password")] Kunde kunde)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Kunder.Add(kunde);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(kunde);
        //}

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kunde kunde = db.Kunder.Find(id);
            if (kunde == null)
            {
                return HttpNotFound();
            }
            return View(kunde);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "KId,Navn,Adresse,Epost,Password")] Kunde kunde)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kunde).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kunde);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kunde kunde = db.Kunder.Find(id);
            if (kunde == null)
            {
                return HttpNotFound();
            }
            return View(kunde);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kunde kunde = db.Kunder.Find(id);
            db.Kunder.Remove(kunde);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineWebShop/Controllers/StoreController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using webshop.Models;
using webshop.Logic;
using System;

namespace webshop.Controllers
{
    public class StoreController : Controller
    {

        public ActionResult Index()
        {

      var db = new DB();
      List<Vare> alleBestillinger = db.listAlleVare();
      return View(alleBestillinger);
    
        }

        //   [Authorize]
      //  public ActionResult Buy(int id)
      //  {
      //   var db = new DB();
      //// Vare vare = db.listAlleVare().Single(a => a.VareId == id);
      ////put the item in to cart
      //List<CartItem> cart = this.AddtoCarts(id) ;
      //      return View(cart);
      //  }

    


    //private List<CartItem> GetCarts()
    //    {
    //  var db = new DB();
    //  var cart = new List<CartItem>{
    //            new CartItem { VareId = 1, CartId = "1", Vare = db.listAlleVare().Single(g => g.VareId == 1) },
    //            new CartItem { VareId = 3, CartId = "1", Vare = db.listAlleVare().Single(g => g.VareId == 3) }
    //        };
    //        return cart;
    //    }
    //private List<CartItem> AddtoCarts(int id)
    //{
    //  var db = new DB();
    //  var Cart = GetCarts();
    //  Cart.Add(new CartItem { VareId = id, CartId = "1", Vare = db.listAlleVare().Single(g => g.VareId == id) });
    //  return Cart;
    //}
  }
}

OnlineWebShop/Views/Customers/Delete.cshtml
@model webshop.Models.Kunde

@{
  ViewBag.Title = "Delete";
}
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Kunde</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Navn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Navn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Adresse)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Adresse)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Epost)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Epost)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

OnlineWebShop/Views/Customers/Details.cshtml
@model webshop.Models.Kunde

    <div>
        <h4>Kunde</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Navn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Navn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Adresse)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Adresse)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Epost)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Epost)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>

OnlineWebShop/Views/Customers/Index.cshtml
@model IEnumerable<webshop.Models.Kunde>

@{
    ViewBag.Title = "show Customers ";
}
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Navn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adresse)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Epost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Navn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adresse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Epost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.KId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.KId })
            </td>
        </tr>
    }
    </table>

OnlineWebShop/Views/Customers/SignIn.cshtml
@model webshop.Models.Kunde
<script src="~/Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(document).on("click", ".signin-btn", function () {
            var form = $(this).closest("form");
            form.submit();
        });
    });
</script>
<h2>Sign In</h2>
<br />
<a href="@Url.Action("Create")">Register new customer</a>
@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
      <label for="Email" class="control-label col-md-2">Email:</label>
      <div class="col-md-10">
        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @type = "email", @maxlength = "40" } })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
      </div>
    </div>
    <div class="form-group">
      <label for="LoginPassword" class="control-label col-md-2">Password:</label>
      <div class="col-md-10">
        @Html.EditorFor(model => model.LoginPassword, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
        @Html.ValidationMessageFor(model => model.LoginPassword, "", new { @class = "text-danger" })
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <a href="javascript:void(0)" class="signin-btn btn btn-default">Sign in</a>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <p>@ViewBag.SignInFailed</p>
      </div>
    </div>
  </div>
}
<a href="@Url.Action("Index", "Store")" class="btn btn-primary">Back</a>